services:
  - type: web
    name: sankhya-opt
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /api/system/status
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3